### PR TITLE
Pass additional org value to sync.

### PR DESCRIPTION
**Pull request by dan-corneanu**
@brunotag The documentation on `sync` is here
https://laravel.com/docs/5.4/eloquent-relationships

I have pushed a PR for #73 , please review and comment.

### CODE REVIEW

**Review by brunotag — COMMENTED** [review]
Hey @dan-corneanu this is what I mean.
It makes it a bit easier to read and reuse.
Thoughts?

**Review by dan-corneanu — COMMENTED** [review]
@brunotag `sync()` is implemented in the ORM framework so adding an extra parameter would be painful. We could override `sync()` but I like `setRoles` better. It communicates clearly what the intent of the method is. 

It would be so much better if we had a context to carry the current `org` and current `user`. But that would mean updating all the php pages. Which I have tried at some point but it is a lot of work.

Let's push this change.

**Comment by tim-hogan** [comment]
>> It would be so much better if we had a context to carry the current org and current user.

This is available in the php $_SESSION array.

**Comment by dan-corneanu** [comment]
Ahh, of course, you are right.

**Comment by brunotag** [comment]
Ok!

**Pull request merged**
