### PR TITLE
Features/bootstrap select optimization

### PR DESCRIPTION
**Pull request by dan-corneanu**
This change:
* removes passive members from the drop down list displayed in the timesheet. Later will also add a script to run at the end of the month and passivate short term members older than **3 month**.
* add a new version of the Daily Timesheet page with the following changes:
** replaces the existing comboboxes with bootstrap-select widgets which allows the user to search through the items in the list. Makes it easier to select the PIC and P2.
** makes buttons a little bit larger to be easier to handle on the tablet.

### CODE REVIEW

**Comment by tim-hogan** [comment]
I am not an expert in JQuery, but had a quick look at bootstrap-select features.   My only concern is the much larger code base and additional files.  So have you considered, additional network and processing required to handle?  Additional network should me measured to ensure we don't go over on Telco Network.

**Comment by dan-corneanu** [comment]
Yes, this is something I was about to discuss with you.

   1. I have included minified versions of all the JS scripting libraries
   and CSS files. They are delivered through CDN and should be stored by the
   browser locally once they are downloaded for the first time. I will measure
   the size and report back.
   2. Brian was happy with the search functionality in the bootstrap select
   because even with all the *passive* members removed from the dropdown
   there are still around 150 entries in the list and it is increasingly
   harder and error prone to scroll on the tablet and tap the correct entry.
   This is why I have rushed a little bit and deployed it without first asking
   you to review.

These being said, are you willing to give it a more in-depth try on your
dev computer and let me know what your thoughts are?
and also review the code changes (I realise they are not small and might be
convoluted in some places but I am happy to answer questions)?

Regards,
Dan

**Comment by dan-corneanu** [comment]
@tim-hogan 
regarding additional network. Here is a breakdown by resource type:
1. first time load when browser cache is empty
 - 16 Requests
 - 29.2KB CSS, 93.8KB JS
2. once JS and CSS files are cached
 - 16 Requests (most of which were cached)
 - 0KB CSS, 0KB JS

**Comment by dan-corneanu** [comment]
@tim-hogan this was deployed in production for quite some time and so far Brian was happy with it.

Do you agree to merge into master? if yes please approve the changes.

**Pull request merged**
